package za.ac.wits.campusnavigator.data.local;

import androidx.annotation.Nullable;
import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * A saved Building in the user-data database (ARCHITECTURE-SPINE.md AD-6, ER diagram).
 * {@code buildingId} is the Building's own stable id -- deliberately not a Room
 * {@code @ForeignKey}, since {@code Building} lives in the separate, bundled
 * {@code CampusDatabase}; Room cannot enforce a cross-database foreign key, so
 * reconciliation (does this id still resolve to a real Building) happens explicitly at
 * read time ({@code GetFavouritesUseCase}), never assumed. Using {@code buildingId} itself
 * as the {@code @PrimaryKey} (not a separate autogenerated id) is what enforces "favouriting
 * an already-favourited Building is a no-op, not a duplicate row" at the schema level.
 * Story 5.1.
 */
@Entity(tableName = "FavouriteEntry")
public class FavouriteEntity {

    @PrimaryKey
    @ColumnInfo(name = "building_id")
    public long buildingId;

    /**
     * Reserved for the PRD's near-term recurring-schedule fast-follow (ARCHITECTURE-SPINE.md
     * Absorb-growth seeds note) -- always {@code null} in V1, read/written by nothing yet.
     */
    @Nullable
    @ColumnInfo(name = "schedule_day")
    public String scheduleDay;
}
