-- Generated by tools/osm/convert_manual_mapping.py from geo1
-- Additive only -- does not touch any existing Node/Edge/Building/BuildingFootprint row.
BEGIN TRANSACTION;
INSERT INTO Node (id, latitude, longitude, campus_id, level_id) VALUES (522, -26.188269, 28.025431, 'wits-main', 'OUTDOOR');
INSERT INTO Node (id, latitude, longitude, campus_id, level_id) VALUES (523, -26.191827, 28.031792, 'wits-main', 'OUTDOOR');
INSERT INTO Node (id, latitude, longitude, campus_id, level_id) VALUES (524, -26.191781, 28.032344, 'wits-main', 'OUTDOOR');
INSERT INTO Node (id, latitude, longitude, campus_id, level_id) VALUES (525, -26.191765, 28.03268, 'wits-main', 'OUTDOOR');
INSERT INTO Edge (id, from_node_id, to_node_id, distance_meters, is_stairs) VALUES (519, 318, 522, 39.00, 0);
INSERT INTO Edge (id, from_node_id, to_node_id, distance_meters, is_stairs) VALUES (520, 456, 523, 9.51, 0);
INSERT INTO Edge (id, from_node_id, to_node_id, distance_meters, is_stairs) VALUES (521, 523, 524, 55.31, 0);
INSERT INTO Edge (id, from_node_id, to_node_id, distance_meters, is_stairs) VALUES (522, 524, 525, 33.57, 0);
INSERT INTO Edge (id, from_node_id, to_node_id, distance_meters, is_stairs) VALUES (523, 525, 247, 11.81, 0);
COMMIT;
