-- Generated by tools/osm/convert_manual_mapping.py from batch2.geojson
-- Node/Edge/new-Building rows are additive only. Any 'correct_building_id'
-- feature UPDATEs that existing Building row and replaces its footprint.
BEGIN TRANSACTION;
INSERT INTO BuildingFootprint (id, building_id, ring_geojson) VALUES (24, 22, '[[28.0251281, -26.1873412], [28.0248373, -26.1873778], [28.0248491, -26.1874442], [28.0251377, -26.1874124], [28.0251281, -26.1873412]]');
COMMIT;
